#!/usr/bin/env python3
"""Synchronize generated version mirrors from the root VERSION file."""
from __future__ import annotations

import json
import re
from pathlib import Path

from versioning import ROOT, VERSION


def write_if_changed(path: Path, text: str) -> None:
    if not text.endswith("\n"):
        text += "\n"
    if path.is_file() and path.read_text(encoding="utf-8") == text:
        return
    path.write_text(text, encoding="utf-8")


def main() -> None:
    for relative in ("runtime/VERSION", "stdlib/VERSION"):
        write_if_changed(ROOT / relative, VERSION)

    package_path = ROOT / "editors/vscode/package.json"
    package = json.loads(package_path.read_text(encoding="utf-8"))
    package["version"] = VERSION
    write_if_changed(package_path, json.dumps(package, indent=2, ensure_ascii=False))

    version_path = ROOT / "compiler/include/ppc/support/version.hpp"
    version_header = version_path.read_text(encoding="utf-8")
    version_header, replacements = re.subn(
        r'(kCompilerVersion\s*=\s*")[^"]+(";)',
        rf'\g<1>{VERSION}\g<2>',
        version_header,
        count=1,
    )
    if replacements != 1:
        raise RuntimeError("cannot synchronize compiler version header")
    write_if_changed(version_path, version_header)

    baseline = json.loads((ROOT / "spec/1.0/stable-api.json").read_text(encoding="utf-8"))
    stable_header = """#ifndef PPC_SUPPORT_STABLE_API_HPP
#define PPC_SUPPORT_STABLE_API_HPP

// Generated by scripts/sync_version.py from spec/1.0/stable-api.json.
// This is the frozen 1.x compatibility floor reported by language-info.
namespace ppc::version {
inline constexpr const char *kStableKeywordsJson = R"punpun_json(%s)punpun_json";
inline constexpr const char *kStableStdlibJson = R"punpun_json(%s)punpun_json";
}  // namespace ppc::version

#endif
""" % (
        json.dumps(baseline["keywords"], separators=(",", ":"), ensure_ascii=False),
        json.dumps(baseline["stdlib_symbols"], separators=(",", ":"), ensure_ascii=False),
    )
    write_if_changed(ROOT / "compiler/include/ppc/support/stable_api.hpp", stable_header)
    print(f"synchronized generated version mirrors -> {VERSION}")


if __name__ == "__main__":
    main()
